### ISSUE TITLE
Multiple exceptions in output

### ISSUE THREAD

**Issue by cfjedimaster** [cflint/CFLint#11]
Not sure why, but I get multiple exceptions when running over a folder.

-------cfml.parsing.cfscript.CFParseException: mismatched input '!' expecting RIGHTPAREN
org.antlr.runtime.tree.RewriteEmptyStreamException: rule primaryExpression
	at org.antlr.runtime.tree.RewriteRuleElementStream._next(RewriteRuleElementStream.java:157)
	at org.antlr.runtime.tree.RewriteRuleElementStream.nextTree(RewriteRuleElementStream.java:144)
	at cfml.parsing.cfscript.CFScriptParser.memberExpressionB(CFScriptParser.java:16378)
	at cfml.parsing.cfscript.CFScriptParser.memberExpression(CFScriptParser.java:16253)
	at cfml.parsing.cfscript.CFScriptParser.unaryExpression(CFScriptParser.java:16136)
	at cfml.parsing.cfscript.CFScriptParser.powerOfExpression(CFScriptParser.java:14837)
	at cfml.parsing.cfscript.CFScriptParser.multiplicativeExpression(CFScriptParser.java:14685)
	at cfml.parsing.cfscript.CFScriptParser.intDivisionExpression(CFScriptParser.java:14572)
	at cfml.parsing.cfscript.CFScriptParser.modExpression(CFScriptParser.java:14450)
	at cfml.parsing.cfscript.CFScriptParser.additiveExpression(CFScriptParser.java:14304)
	at cfml.parsing.cfscript.CFScriptParser.concatenationExpression(CFScriptParser.java:14191)
	at cfml.parsing.cfscript.CFScriptParser.equalityExpression(CFScriptParser.java:12382)
	at cfml.parsing.cfscript.CFScriptParser.notExpression(CFScriptParser.java:12304)
	at cfml.parsing.cfscript.CFScriptParser.andExpression(CFScriptParser.java:12141)
	at cfml.parsing.cfscript.CFScriptParser.orExpression(CFScriptParser.java:12019)
	at cfml.parsing.cfscript.CFScriptParser.xorExpression(CFScriptParser.java:11908)
	at cfml.parsing.cfscript.CFScriptParser.equivalentExpression(CFScriptParser.java:11797)
	at cfml.parsing.cfscript.CFScriptParser.impliesExpression(CFScriptParser.java:11549)
	at cfml.parsing.cfscript.CFScriptParser.assignmentExpression(CFScriptParser.java:10662)
	at cfml.parsing.cfscript.CFScriptParser.localAssignmentExpression(CFScriptParser.java:10588)
	at cfml.parsing.cfscript.CFScriptParser.statement(CFScriptParser.java:4528)
	at cfml.parsing.cfscript.CFScriptParser.compoundStatement(CFScriptParser.java:4126)
	at cfml.parsing.cfscript.CFScriptParser.functionDeclaration(CFScriptParser.java:1888)
	at cfml.parsing.cfscript.CFScriptParser.element(CFScriptParser.java:1605)
	at cfml.parsing.cfscript.CFScriptParser.componentGuts(CFScriptParser.java:4238)
	at cfml.parsing.cfscript.CFScriptParser.componentDeclaration(CFScriptParser.java:678)
	at cfml.parsing.cfscript.CFScriptParser.scriptBlock(CFScriptParser.java:524)
	at cfml.parsing.CFMLParser.parseScript(CFMLParser.java:315)
	at com.cflint.CFLint.process(CFLint.java:147)
	at com.cflint.CFLint.scan(CFLint.java:109)
	at com.cflint.CFLint.scan(CFLint.java:103)
	at com.cflint.CFLint.scan(CFLint.java:103)
	at com.cflint.CFLint.scan(CFLint.java:103)
	at com.cflint.CFLint.scan(CFLint.java:103)
	at com.cflint.CFLint.scan(CFLint.java:103)
	at com.cflint.CFLint.scan(CFLint.java:97)
	at com.cflint.main.CFLintMain.execute(CFLintMain.java:242)
	at com.cflint.main.CFLintMain.main(CFLintMain.java:157)

**Comment by ryaneberly** [comment]
fixed the parsing issues in the antlr4 branch. 
Hope to release soon.
