### ISSUE TITLE
Parse issue

### ISSUE THREAD

**Issue by sjmatta** [cflint/CFLint#140]
Trying to figure out if I'm doing something wrong or if there is a bug.

I get a FILE_ERROR attempting to parse the CFC in [this ZIP file](https://github.com/cflint/CFLint/files/70011/Inspection.zip). I also get a null pointer exception parsing it through stdin, though I suspect it's the same root cause.

Commenting out `var rc.bob = "";` makes it parseable. So does parsing just `var rc.bob = "";` by itself.

```C:\Users\smatta.EVENTCENTRIC\Downloads
λ java -jar c:\stephen\linter-cflint\bin\CFLint-0.6.1-all.jar -q -e -stdout -xml -stdin
component {

        public void function detail() {

                var rc.bob = '';

        }
}
^Z
log4j:WARN No appenders could be found for logger (net.htmlparser.jericho).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NullPointerException
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitLocalAssignmentExpression(CFExpressionVisitor.java:174)
        at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitLocalAssignmentExpression(CFExpressionVisitor.java:63)
        at cfml.CFSCRIPTParser$LocalAssignmentExpressionContext.accept(CFSCRIPTParser.java:4166)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:239)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:89)
        at cfml.CFSCRIPTParser$StatementContext.accept(CFSCRIPTParser.java:1592)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitCompoundStatement(CFScriptStatementVisitor.java:216)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitCompoundStatement(CFScriptStatementVisitor.java:89)
        at cfml.CFSCRIPTParser$CompoundStatementContext.accept(CFSCRIPTParser.java:1425)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitFunctionDeclaration(CFScriptStatementVisitor.java:141)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitFunctionDeclaration(CFScriptStatementVisitor.java:89)
        at cfml.CFSCRIPTParser$FunctionDeclarationContext.accept(CFSCRIPTParser.java:520)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at cfml.CFSCRIPTParserBaseVisitor.visitElement(CFSCRIPTParserBaseVisitor.java:41)
        at cfml.CFSCRIPTParser$ElementContext.accept(CFSCRIPTParser.java:442)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at cfml.CFSCRIPTParserBaseVisitor.visitComponentGuts(CFSCRIPTParserBaseVisitor.java:132)
        at cfml.CFSCRIPTParser$ComponentGutsContext.accept(CFSCRIPTParser.java:1491)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitComponentDeclaration(CFScriptStatementVisitor.java:104)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitComponentDeclaration(CFScriptStatementVisitor.java:89)
        at cfml.CFSCRIPTParser$ComponentDeclarationContext.accept(CFSCRIPTParser.java:329)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at cfml.CFSCRIPTParserBaseVisitor.visitScriptBlock(CFSCRIPTParserBaseVisitor.java:20)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:97)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:89)
        at cfml.CFSCRIPTParser$ScriptBlockContext.accept(CFSCRIPTParser.java:237)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at cfml.parsing.CFMLParser.parseScript(CFMLParser.java:398)
        at com.cflint.CFLint.process(CFLint.java:266)
        at com.cflint.main.CFLintMain.execute(CFLintMain.java:304)
        at com.cflint.main.CFLintMain.main(CFLintMain.java:183)```

**Comment by sjmatta** [comment]
Apologies - this may have been better suited to cfparser/cfparser. I'm still looking into it myself.

**Comment by ryaneberly** [comment]
No worries.  it is a cfparser question.   But is that valid to var a field on a structure?

This would be valid:
   var rc= {};
   rc.bob = '';

**Comment by sjmatta** [comment]
No :) I was just trying to distill it down to the smallest possible code that would break. Unfortunately, I still get the same error with:
```
component {
	public void function detail() {
		var rc = {};
		var rc.bob = '';
	}
}
```

**Comment by ryaneberly** [comment]
I haven't tried it on the server,  but I don't think the 2nd var is legit, is it?   The syntax would certainly be a little odd, since bob is already scoped under rc.

**Comment by sjmatta** [comment]
Ah, good point! Yes, taking off the `rc.` fixes the parse issue. I think it would be good for the linter to warn there's an error on that specific line instead of erroring out, but the original issue was just my code. Thanks!

**Comment by ryaneberly** [comment]
I agree with that :-)  Thanks!

**Comment by ryaneberly** [comment]
@sjmatta  after all that, I tried it with the latest version of cfparser and CFLint.  This was improved a while back and just released last week!

You should see something like:
"End of statement(;) expected instead of ."
In file component.cfc , line 5
In c:\temp\cfc\component.cfc 
At line : 5
