### ISSUE TITLE
multiple location members in JSON output

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#158]
I was parsing the JSON output of CFLINT with Visual Basic. This didn't work with the JSON output by a recent CFLINT version, as there are multiple `location` members within a single error message. This seems to be limited to the `PARSE_ERROR` finding.
```{
  "severity" : "ERROR",
  "id" : "PARSE_ERROR",
  "message" : "PARSE_ERROR",
  "category" : "CFLINT",
  "abbrev" : "PE",
  "location" : {
    "file" : "D:\\projects\\source\\app\\ApplicationConfigLoader.cfc\r\n",
    "fileName" : "ApplicationConfigLoader.cfc\r\n",
    "column" : "30",
    "line" : "25",
    "message" : "Unable to parse",
    "variable" : "",
    "expression" : "extraneous input '(' expecting {<EOF>, CONTAINS, GT, GTE, LTE, LT, EQ, NEQ, OR, EQV, XOR, AND, '.', '++', '--', '||', '&&', '[', '?'}"
  },
  "location" : {
    "file" : "D:\\projects\\source\\app\\ApplicationConfigLoader.cfc\r\n",
    "fileName" : "ApplicationConfigLoader.cfc\r\n",
    "column" : "30",
    "line" : "26",
    "message" : "Unable to parse",
    "variable" : "",
    "expression" : "extraneous input '(' expecting {<EOF>, CONTAINS, GT, GTE, LTE, LT, EQ, NEQ, OR, EQV, XOR, AND, '.', '++', '--', '||', '&&', '[', '?'}"
  }
}
```

**Comment by ryaneberly** [comment]
fixed in dev.branch

**Comment by bardware** [comment]
dev does compile but does not run. When I run maven ` -Dmaven.test.skip=true` and use the jar I get the same error.
Tests fail like so:
```
java.lang.NoClassDefFoundError: org/jdom/JDOMException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cfml.parsing.cfmentat.tag.CFMLTags.register(CFMLTags.java:45)
	at cfml.parsing.CFMLSource.<init>(CFMLSource.java:24)
	at com.cflint.integration.TestCFMLParse.test(TestCFMLParse.java:11)
```

**Comment by ryaneberly** [comment]
a clean build revealed my mistake.  fixed.  thanks.
