### ISSUE TITLE
Where does cflint-ui come from?

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#212]
Hi,

I wondered where `cflint-ui.bat` might come from.
I got the impression it's being generated by a certain call to maven
I tried `mvn -e -X package appassembler:assemble` and got:

```
[ERROR] Failed to execute goal org.codehaus.mojo:appassembler-maven-plugin:1.10:assemble (default-cli) on project CFLint: The parameters 'programs' for goal org.codehaus.mojo:appassembler-maven-plugin:1.10:assemble are missing or invalid -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:appassembler-maven-plugin:1.10:assemble (default-cli) on project CFLint: The parameters 'programs' for goal org.codehaus.mojo:appassembler-maven-plugin:1.10:assemble are missing or invalid
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:220)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginParameterException: The parameters 'programs' for goal org.codehaus.mojo:appassembler-maven-plugin:1.10:assemble are missing or invalid
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:668)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:621)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
```

Compilation of the classes and running tests seems to work. There is a file `target\classes\com\cflint\main\CFLintMain.class`.

Best,
Bernhard

**Comment by ryaneberly** [comment]
the ui bat comes from the pom (lines 254-161)
`mvn clean package`
should work for you

I'm not a maven expert, I can't speak to the your choice of parms.

The steps we use to deploy a release are in the comment at the bottom of the pom. (jerronjames set it up)

**Comment by bardware** [comment]
I modified line 243 to read
<phase>package</phase>
and called `mvn clean package -P deploy`
That worked.

**Comment by ryaneberly** [comment]
Any idea what is different about your case?  Should we make that change to
the CFLint source?

**Comment by bardware** [comment]
I'm not experienced in mvn, sorry. Generation of runnable files during the packaging phase just seemed more right to me that during the integration-testing phase. Was a try that worked.

**Comment by ryaneberly** [comment]
changed the pom.  Thanks!
