### ISSUE TITLE
NoViableAltException java.lang.NullPointerException

### ISSUE THREAD

**Issue by laserbyte** [cflint/CFLint#22]
I'm getting multiple NoViableAltException java.lang.NullPointerException errors like the following when scanning a folder:

```
-------NoViableAltException(94@[])
java.lang.NullPointerException
        at org.antlr.runtime.tree.BaseTreeAdaptor.isNil(BaseTreeAdaptor.java:70)
        at org.antlr.runtime.tree.CommonTreeNodeStream.nextElement(CommonTreeNodeStream.java:91)
        at org.antlr.runtime.misc.LookaheadStream.fill(LookaheadStream.java:107)
        at org.antlr.runtime.misc.LookaheadStream.syncAhead(LookaheadStream.java:101)
        at org.antlr.runtime.misc.LookaheadStream.LT(LookaheadStream.java:122)
        at org.antlr.runtime.tree.CommonTreeNodeStream.LA(CommonTreeNodeStream.java:120)
        at cfml.parsing.cfscript.CFScriptTree.scriptBlock(CFScriptTree.java:249)
        at cfml.parsing.CFMLParser.parseScript(CFMLParser.java:329)
        at com.cflint.CFLint.process(CFLint.java:280)
        at com.cflint.CFLint.processStack(CFLint.java:197)
        at com.cflint.CFLint.process(CFLint.java:275)
        at com.cflint.CFLint.processStack(CFLint.java:197)
        at com.cflint.CFLint.process(CFLint.java:284)
        at com.cflint.CFLint.processStack(CFLint.java:197)
        at com.cflint.CFLint.process(CFLint.java:284)
        at com.cflint.CFLint.processStack(CFLint.java:197)
        at com.cflint.CFLint.process(CFLint.java:284)
        at com.cflint.CFLint.processStack(CFLint.java:197)
        at com.cflint.CFLint.process(CFLint.java:188)
        at com.cflint.CFLint.scan(CFLint.java:145)
        at com.cflint.CFLint.scan(CFLint.java:139)
        at com.cflint.CFLint.scan(CFLint.java:116)
        at com.cflint.main.CFLintMain.execute(CFLintMain.java:251)
        at com.cflint.main.CFLintMain.main(CFLintMain.java:164)
```

**Comment by ryaneberly** [comment]
closed.  need an example to duplicate this one

**Comment by laserbyte** [comment]
Here is an example if you wouldn't mind re-opening the issue.

Thanks!

```coldfusion
<cfset lParams = "name,addy,city,state,zip" />

<cfquery name="qPeople" datasource="#request.app.datasource.name#">
	select *
	from people
	where 1 = 1
	<cfloop index="i" list="#lParams#" >
		<cfif url[#i#] neq 'null' AND Trim(url[#i#]) neq "">
			<cfif i eq "name">
				lastname LIKE <cfqueryparam cfsqltype="cf_sql_varchar" value="%#url[i]#%" />
		</cfif>
	</cfloop>
</cfquery>
```

**Comment by ryaneberly** [comment]
Thanks laserbyte,
    Reopened

**Comment by ryaneberly** [comment]
fixed in antlr4 branch, releasing soon.
