### ISSUE TITLE
Null pointer Exception

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#408]
the following snippet from https://github.com/bennadel/POIUtility.cfc/blob/master/coldfusion_mx7/POIUtility.cfc#L804 cases a NPE

```
<cfscript>
	// Loop over each CSS pair.
	for (
		local.PairIterator = local.Pairs.Iterator() ;
		local.PairIterator.HasNext() ;
		){
	}
</cfscript>
```

java.lang.NullPointerException
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitForStatement(CFScriptStatementVisitor.java:310)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitForStatement(CFScriptStatementVisitor.java:95)
        at cfml.CFSCRIPTParser$ForStatementContext.accept(CFSCRIPTParser.java:2883)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:256)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:95)
        at cfml.CFSCRIPTParser$StatementContext.accept(CFSCRIPTParser.java:2239)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at cfml.CFSCRIPTParserBaseVisitor.visitElement(CFSCRIPTParserBaseVisitor.java:41)
        at cfml.CFSCRIPTParser$ElementContext.accept(CFSCRIPTParser.java:485)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at cfml.CFSCRIPTParserBaseVisitor.visitScriptBlock(CFSCRIPTParserBaseVisitor.java:20)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:103)
        at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:95)
        at cfml.CFSCRIPTParser$ScriptBlockContext.accept(CFSCRIPTParser.java:254)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at cfml.parsing.CFMLParser.parseScript(CFMLParser.java:480)
        at com.cflint.CFLint.process(CFLint.java:441)
        at com.cflint.CFLint.processStack(CFLint.java:323)
        at com.cflint.CFLint.process(CFLint.java:296)
        at com.cflint.CFLint.scan(CFLint.java:250)
        at com.cflint.CFLint.scan(CFLint.java:176)
        at com.cflint.main.CFLintMain.execute(CFLintMain.java:436)
        at com.cflint.main.CFLintMain.main(CFLintMain.java:282)

**Comment by zspitzer** [comment]
also, tracking down which file was causing the NPE was difficult, is there a way to show each file being processed? -verbose doesn't

**Comment by TheRealAgentK** [comment]
I was going to implement that with a new -debug flag. Probably in 1.3 .

**Comment by ryaneberly** [comment]
@TheRealAgentK That's good.  
com.cflint.CFLint.process(String, String) should also wrap exceptions coming out of it with the file name so you don't need to be in debug mode to figure out what file failed.  Perhaps it should simply report a PARSE_ERROR in this case as well.

**Comment by ryaneberly** [comment]
fixed in master.
