### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by AntoineGagnon** [cflint/CFLint#56]
Here is the build failure I get when trying to simply install CFLint locally :

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building CFLint 0.4.0
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact ant:ant:jar:1.7.0 has been relocated to org.apache.ant:ant:jar:1.7.0
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ CFLint ---
[INFO] Deleting /Users/agagnon/testFolder/CFLint/target
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (default) @ CFLint ---
[INFO] Copying jdom-1.0.jar to /Users/agagnon/testFolder/CFLint/target/dependency/jdom-1.0.jar
[INFO] Copying antlr-runtime-3.3.jar to /Users/agagnon/testFolder/CFLint/target/dependency/antlr-runtime-3.3.jar
[INFO] Copying log4j-1.2.17.jar to /Users/agagnon/testFolder/CFLint/target/dependency/log4j-1.2.17.jar
[INFO] Copying ant-launcher-1.7.0.jar to /Users/agagnon/testFolder/CFLint/target/dependency/ant-launcher-1.7.0.jar
[INFO] Copying ant-1.7.0.jar to /Users/agagnon/testFolder/CFLint/target/dependency/ant-1.7.0.jar
[INFO] Copying junit-4.11.jar to /Users/agagnon/testFolder/CFLint/target/dependency/junit-4.11.jar
[INFO] Copying javolution-5.2.6.jar to /Users/agagnon/testFolder/CFLint/target/dependency/javolution-5.2.6.jar
[INFO] Copying stringtemplate-4.0.2.jar to /Users/agagnon/testFolder/CFLint/target/dependency/stringtemplate-4.0.2.jar
[INFO] Copying pf4j-0.6.jar to /Users/agagnon/testFolder/CFLint/target/dependency/pf4j-0.6.jar
[INFO] Copying activation-1.1.jar to /Users/agagnon/testFolder/CFLint/target/dependency/activation-1.1.jar
[INFO] Copying jaxb-impl-2.1.8.jar to /Users/agagnon/testFolder/CFLint/target/dependency/jaxb-impl-2.1.8.jar
[INFO] Copying json-simple-1.1.jar to /Users/agagnon/testFolder/CFLint/target/dependency/json-simple-1.1.jar
[INFO] Copying ST4-4.0.8.jar to /Users/agagnon/testFolder/CFLint/target/dependency/ST4-4.0.8.jar
[INFO] Copying javolution-5.5.1.jar to /Users/agagnon/testFolder/CFLint/target/dependency/javolution-5.5.1.jar
[INFO] Copying commons-cli-1.2.jar to /Users/agagnon/testFolder/CFLint/target/dependency/commons-cli-1.2.jar
[INFO] Copying slf4j-log4j12-1.7.5.jar to /Users/agagnon/testFolder/CFLint/target/dependency/slf4j-log4j12-1.7.5.jar
[INFO] Copying antlr4-4.5.jar to /Users/agagnon/testFolder/CFLint/target/dependency/antlr4-4.5.jar
[INFO] Copying cfml.parsing-2.0.0-SNAPSHOT.jar to /Users/agagnon/testFolder/CFLint/target/dependency/cfml.parsing-2.0.0-SNAPSHOT.jar
[INFO] Copying hamcrest-core-1.3.jar to /Users/agagnon/testFolder/CFLint/target/dependency/hamcrest-core-1.3.jar
[INFO] Copying slf4j-api-1.7.5.jar to /Users/agagnon/testFolder/CFLint/target/dependency/slf4j-api-1.7.5.jar
[INFO] Copying commons-logging-api-1.1.jar to /Users/agagnon/testFolder/CFLint/target/dependency/commons-logging-api-1.1.jar
[INFO] Copying cfparser-2.0.0-SNAPSHOT.pom to /Users/agagnon/testFolder/CFLint/target/dependency/cfparser-2.0.0-SNAPSHOT.pom
[INFO] Copying stax-api-1.0-2.jar to /Users/agagnon/testFolder/CFLint/target/dependency/stax-api-1.0-2.jar
[INFO] Copying commons-logging-1.2.jar to /Users/agagnon/testFolder/CFLint/target/dependency/commons-logging-1.2.jar
[INFO] Copying org.abego.treelayout.core-1.0.1.jar to /Users/agagnon/testFolder/CFLint/target/dependency/org.abego.treelayout.core-1.0.1.jar
[INFO] Copying cfml.dictionary-2.0.0-SNAPSHOT.jar to /Users/agagnon/testFolder/CFLint/target/dependency/cfml.dictionary-2.0.0-SNAPSHOT.jar
[INFO] Copying antlr4-runtime-4.5.jar to /Users/agagnon/testFolder/CFLint/target/dependency/antlr4-runtime-4.5.jar
[INFO] Copying jaxb-api-2.1.jar to /Users/agagnon/testFolder/CFLint/target/dependency/jaxb-api-2.1.jar
[INFO] Copying jericho-html-3.3.jar to /Users/agagnon/testFolder/CFLint/target/dependency/jericho-html-3.3.jar
[INFO] Copying jdom-1.1.3.jar to /Users/agagnon/testFolder/CFLint/target/dependency/jdom-1.1.3.jar
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ CFLint ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 13 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ CFLint ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 39 source files to /Users/agagnon/testFolder/CFLint/target/classes
[INFO] /Users/agagnon/testFolder/CFLint/src/main/java/com/cflint/tools/CFLintFilter.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/agagnon/testFolder/CFLint/src/main/java/com/cflint/tools/CFLintFilter.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ CFLint ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ CFLint ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 25 source files to /Users/agagnon/testFolder/CFLint/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/agagnon/testFolder/CFLint/src/test/java/com/cflint/TestFunctionLengthChecker.java:[16,31] cannot find symbol
  symbol:   class Temp
  location: package com.cflint.plugins.core
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.272 s
[INFO] Finished at: 2015-05-28T10:24:39-05:00
[INFO] Final Memory: 22M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project CFLint: Compilation failure
[ERROR] /Users/agagnon/testFolder/CFLint/src/test/java/com/cflint/TestFunctionLengthChecker.java:[16,31] cannot find symbol
[ERROR] symbol:   class Temp
[ERROR] location: package com.cflint.plugins.core
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project CFLint: Compilation failure
/Users/agagnon/testFolder/CFLint/src/test/java/com/cflint/TestFunctionLengthChecker.java:[16,31] cannot find symbol
  symbol:   class Temp
  location: package com.cflint.plugins.core

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/Users/agagnon/testFolder/CFLint/src/test/java/com/cflint/TestFunctionLengthChecker.java:[16,31] cannot find symbol
  symbol:   class Temp
  location: package com.cflint.plugins.core

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:911)
	at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:153)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by ryaneberly** [comment]
Caused by a check in on 
#49 

We'll look into it.
Thanks!

**Comment by jerronjames** [comment]
just ran "mvn clean install" and it built fine. Not sure why it's not working for you. Have to look at it a little more when I get some time.

**Comment by AntoineGagnon** [comment]
Using the quickstart Java methods works fine, that¹s what I¹m currently
using right now but I wanted to give the MVN version a go.

Regards,

Antoine

From:  jerronjames <notifications@github.com>
Reply-To:  cflint/CFLint
<reply+007686442d630252972da05805a8f716904d269e9d67b6e492cf00000001117f46159
2a169ce04e2f3d0@reply.github.com>
Date:  Thursday, May 28, 2015 at 4:09 PM
To:  cflint/CFLint <CFLint@noreply.github.com>
Cc:  AntoineGagnon <antoine@gagnon.fr>
Subject:  Re: [CFLint] Build failure (#56)


just ran "mvn clean install" and it built fine. Not sure why it's not
working for you. Have to look at it a little more when I get some time.


Reply to this email directly or view it on GitHub
<https://github.com/cflint/CFLint/issues/56#issuecomment-106600278> .

**Comment by ryaneberly** [comment]
Jerron, you probably have the Temp class in your workspace (not checked in).

See what's in your git staging view.

**Comment by jerronjames** [comment]
left a reference inside a test that shouldn't have been there. Should be fixed now if you want to try it out.

**Comment by ryaneberly** [comment]
Thanks :-)

**Comment by AntoineGagnon** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

Perfect ! Thanks guys, the issue resolving was really quick !
