### ISSUE TITLE
 Message definition not found for [AVOID_USING_CREATEOBJECT]

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#572]
getting a heap of repeated errors with 1.4.0 (the error is repeated for a whole range of checkers, not just CFXTagChecker)

java.lang.NullPointerException: Message definition not found for [AVOID_USING_CREATEOBJECT] in CFXTagChecker
        at com.cflint.CFLint.reportRule(CFLint.java:1326)
        at com.cflint.CFLint.scanExpression(CFLint.java:1022)
        at com.cflint.CFLint.process(CFLint.java:775)
        at com.cflint.CFLint.process(CFLint.java:772)
        at com.cflint.CFLint.process(CFLint.java:515)
        at com.cflint.CFLint.processStack(CFLint.java:416)
        at com.cflint.CFLint.process(CFLint.java:476)
        at com.cflint.CFLint.processStack(CFLint.java:416)
        at com.cflint.CFLint.process(CFLint.java:611)
        at com.cflint.CFLint.processStack(CFLint.java:416)
        at com.cflint.CFLint.process(CFLint.java:629)
        at com.cflint.CFLint.processStack(CFLint.java:416)
        at com.cflint.CFLint.process(CFLint.java:522)
        at com.cflint.CFLint.processStack(CFLint.java:416)
        at com.cflint.CFLint.process(CFLint.java:551)
        at com.cflint.CFLint.processStack(CFLint.java:398)
        at com.cflint.CFLint.process(CFLint.java:341)
        at com.cflint.CFLint.scan(CFLint.java:294)
        at com.cflint.CFLint.scan(CFLint.java:205)
        at com.cflint.api.CFLintAPI.scan(CFLintAPI.java:65)
        at com.cflint.cli.CFLintCLI.execute(CFLintCLI.java:371)
        at com.cflint.cli.CFLintCLI.main(CFLintCLI.java:339)

**Comment by zspitzer** [comment]
I've been trying to create a reduced testcase for this problem, i've managed to narrow it down
to whitespace. remove a couple of blank new lines in the middle of a function and it stops blowing up.

I don't want to share this file publically, but I'm happy to share the file privately for testing, ping me at zac.spitzer@gmail.com
