### ISSUE TITLE
NPE parsing cfsilent with bufferoutput attribute

### ISSUE THREAD

**Issue by sbleon** [cflint/CFLint#645]
File:
```
<cfsilent bufferoutput="true"></cfsilent>
```

Result:
```
java.lang.NullPointerException
	at com.cflint.tools.CFMLTagInfo.isAssignmentAttribute(CFMLTagInfo.java:61)
	at com.cflint.tools.CFMLTagInfo.isExpressionAttribute(CFMLTagInfo.java:96)
	at com.cflint.tools.CFMLTagInfo.isExpressionAttribute(CFMLTagInfo.java:81)
	at com.cflint.CFLint.unpackTagExpressions(CFLint.java:681)
	at com.cflint.CFLint.process(CFLint.java:624)
	at com.cflint.CFLint.processStack(CFLint.java:399)
	at com.cflint.CFLint.process(CFLint.java:342)
	at com.cflint.CFLint.scan(CFLint.java:295)
	at com.cflint.CFLint.scan(CFLint.java:206)
	at com.cflint.api.CFLintAPI.scan(CFLintAPI.java:65)
	at com.cflint.cli.CFLintCLI.execute(CFLintCLI.java:371)
	at com.cflint.cli.CFLintCLI.main(CFLintCLI.java:339)
Error: "null" Location: com.cflint.tools.CFMLTagInfo.isAssignmentAttribute(CFMLTagInfo.java:61)
Issue
Severity:ERROR
Message code:PARSE_ERROR
	File:/Users/leon/code/csubs/internal/querytool.cfm
	Column:1
	Line:1
		Message:Unable to parse
		Variable:'null' in function: 
		Expression:<cfsilent bufferoutput="true">


Total files:1
Total lines:2

Issue counts:1
PARSE_ERROR:1

Total issues:1
Total errors:1
```

**Comment by sbleon** [comment]
Still occurs with current code in `dev` branch.
