### ISSUE TITLE
NPE parsing `var` declaration with no assignment

### ISSUE THREAD

**Issue by sbleon** [cflint/CFLint#648]
File:
```
component {
  function test () {
	  var foo.bar('baz');
  }
}
```

Result:
```
com.cflint.exception.CFLintScanException: java.lang.NullPointerException
	at com.cflint.CFLint.process(CFLint.java:347)
	at com.cflint.CFLint.scan(CFLint.java:295)
	at com.cflint.CFLint.scan(CFLint.java:206)
	at com.cflint.api.CFLintAPI.scan(CFLintAPI.java:65)
	at com.cflint.cli.CFLintCLI.execute(CFLintCLI.java:371)
	at com.cflint.cli.CFLintCLI.main(CFLintCLI.java:339)
Caused by: java.lang.NullPointerException
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitLocalAssignmentExpression(CFExpressionVisitor.java:174)
	at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitLocalAssignmentExpression(CFExpressionVisitor.java:77)
	at cfml.CFSCRIPTParser$LocalAssignmentExpressionContext.accept(CFSCRIPTParser.java:5480)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:278)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$StatementContext.accept(CFSCRIPTParser.java:2352)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitCompoundStatement(CFScriptStatementVisitor.java:254)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitCompoundStatement(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$CompoundStatementContext.accept(CFSCRIPTParser.java:2179)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitFunctionDeclaration(CFScriptStatementVisitor.java:176)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitFunctionDeclaration(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$FunctionDeclarationContext.accept(CFSCRIPTParser.java:642)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.CFSCRIPTParserBaseVisitor.visitElement(CFSCRIPTParserBaseVisitor.java:48)
	at cfml.CFSCRIPTParser$ElementContext.accept(CFSCRIPTParser.java:563)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.CFSCRIPTParserBaseVisitor.visitComponentGuts(CFSCRIPTParserBaseVisitor.java:160)
	at cfml.CFSCRIPTParser$ComponentGutsContext.accept(CFSCRIPTParser.java:2245)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitComponentDeclaration(CFScriptStatementVisitor.java:115)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitComponentDeclaration(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$ComponentDeclarationContext.accept(CFSCRIPTParser.java:431)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.CFSCRIPTParserBaseVisitor.visitScriptBlock(CFSCRIPTParserBaseVisitor.java:20)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:108)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$ScriptBlockContext.accept(CFSCRIPTParser.java:257)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.CFMLParser.parseScript(CFMLParser.java:539)
	at com.cflint.CFLint.process(CFLint.java:338)
	... 5 more
Error: "java.lang.NullPointerException" Location: com.cflint.CFLint.process(CFLint.java:347)
```

Version 1.4.1.

**Comment by sbleon** [comment]
Workaround: Remove the unnecessary `var`.

**Comment by KamasamaK** [comment]
If the `var` here doesn't do anything, I don't think this is worth addressing. In that case, it's not a proper language construct and one of the CFML engines just happens to ignore it.

**Comment by sbleon** [comment]
Yeah, that's a good point. It's not really valid code, but it seems to work OK in Lucee 4.5/5. Still, I'd like to see a PARSE_ERROR for any invalid code, rather than a NullPointerException. 

Oddly, ACF's compile also produces an NPE when compiling similar code: https://trycf.com/gist/5c1ad2a8d21d222366ec4e1ce4f57b00/acf2018

**Comment by KamasamaK** [comment]
If the NPE is not being caught then that is an issue worth addressing.

You should really be testing with the latest `dev` snapshot before reporting to ensure that the issue has not already been fixed. I've run your sample on the 1.5.0 snapshot through the CLI, and it appears to be able to parse.

**Comment by sbleon** [comment]
Is there a place where I can download a JAR of the dev branch? I haven't
gotten set up to build the project myself yet.

**Comment by KamasamaK** [comment]
@sbleon No, snapshots don't get releases. Building is very simple. You just need JDK8 installed and run the command `gradlew build`. See [Building CFLint](https://github.com/cflint/CFLint#building-cflint).
