### ISSUE TITLE
NPE parsing `switch` with a negative number as a `case`

### ISSUE THREAD

**Issue by sbleon** [cflint/CFLint#649]
File:
```
component {
  switch (foo) {
    case -50:
      break;
  }
}
```

Result:
```
com.cflint.exception.CFLintScanException: java.lang.NullPointerException
	at com.cflint.CFLint.process(CFLint.java:347)
	at com.cflint.CFLint.scan(CFLint.java:295)
	at com.cflint.CFLint.scan(CFLint.java:206)
	at com.cflint.api.CFLintAPI.scan(CFLintAPI.java:65)
	at com.cflint.cli.CFLintCLI.execute(CFLintCLI.java:371)
	at com.cflint.cli.CFLintCLI.main(CFLintCLI.java:339)
Caused by: java.lang.NullPointerException
	at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitConstantExpression(CFExpressionVisitor.java:142)
	at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitConstantExpression(CFExpressionVisitor.java:145)
	at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitConstantExpression(CFExpressionVisitor.java:77)
	at cfml.CFSCRIPTParser$ConstantExpressionContext.accept(CFSCRIPTParser.java:3428)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitCaseStatement(CFScriptStatementVisitor.java:393)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitCaseStatement(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$CaseStatementContext.accept(CFSCRIPTParser.java:3619)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitSwitchStatement(CFScriptStatementVisitor.java:374)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitSwitchStatement(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$SwitchStatementContext.accept(CFSCRIPTParser.java:3542)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:282)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$StatementContext.accept(CFSCRIPTParser.java:2352)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.CFSCRIPTParserBaseVisitor.visitElement(CFSCRIPTParserBaseVisitor.java:48)
	at cfml.CFSCRIPTParser$ElementContext.accept(CFSCRIPTParser.java:563)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.CFSCRIPTParserBaseVisitor.visitComponentGuts(CFSCRIPTParserBaseVisitor.java:160)
	at cfml.CFSCRIPTParser$ComponentGutsContext.accept(CFSCRIPTParser.java:2245)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitComponentDeclaration(CFScriptStatementVisitor.java:115)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitComponentDeclaration(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$ComponentDeclarationContext.accept(CFSCRIPTParser.java:431)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.CFSCRIPTParserBaseVisitor.visitScriptBlock(CFSCRIPTParserBaseVisitor.java:20)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:108)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$ScriptBlockContext.accept(CFSCRIPTParser.java:257)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.CFMLParser.parseScript(CFMLParser.java:539)
	at com.cflint.CFLint.process(CFLint.java:338)
	... 5 more
Error: "java.lang.NullPointerException" Location: com.cflint.CFLint.process(CFLint.java:347)
```

Version 1.4.1

**Comment by sbleon** [comment]
Possible workaround: put quotes around the negative number.

**Comment by KamasamaK** [comment]
Duplicates #623

**Comment by sbleon** [comment]
Thanks, @KamasamaK . Sorry I didn't spot that.
