### ISSUE TITLE
Error when reading config file

### ISSUE THREAD

**Issue by justinmclean** [cflint/CFLint#69]
When running with the supplied config file like so:
java -jar ./target/CFLint-0.5.0-all.jar  -file test.cfm -text -configfile ./src/main/resources/cflint.definition.xml  

This error occurs:
Exception in thread "main" java.lang.ClassCastException: com.cflint.config.CFLintPluginInfo cannot be cast to com.cflint.config.CFLintConfig
	at com.cflint.main.CFLintMain.execute(CFLintMain.java:243)
	at com.cflint.main.CFLintMain.main(CFLintMain.java:177)

**Comment by jerronjames** [comment]
In the wiki on here, there is a sample config file. You can use this outside of the CFLint folder. the cflint.definition.xml is setup differently than the type of config file the system is looking for.

**Comment by justinmclean** [comment]
Thanks for that. After looking at this page I managed to get it working.
https://github.com/cflint/CFLint/wiki/Include-Exclude-Rules-Using-External-XML-File
