### ISSUE TITLE
Catch java exception when try to check folder

### ISSUE THREAD

**Issue by spanteleyko** [cflint/CFLint#705]
Hello
I have some error when I Try to check directory:
`java -jar c:\temp\cflint-1.5.0-all.jar -folder c:\repo\fork\ -quiet -text -stdout`

`java.lang.ClassCastException: cfml.parsing.cfscript.CFFunctionExpression cannot be cast to cfml.parsing.cfscript.CFIdentifier
        at cfml.parsing.cfscript.CFFullVarExpression.getIdentifier(CFFullVarExpression.java:31)
        at com.cflint.plugins.core.ArgVarChecker.expression(ArgVarChecker.java:32)
        at com.cflint.CFLint.process(CFLint.java:1107)
        at com.cflint.CFLint.process(CFLint.java:1145)
        at com.cflint.CFLint.process(CFLint.java:772)
        at com.cflint.CFLint.process(CFLint.java:509)
        at com.cflint.CFLint.processStack(CFLint.java:415)
        at com.cflint.CFLint.process(CFLint.java:516)
        at com.cflint.CFLint.processStack(CFLint.java:415)
        at com.cflint.CFLint.process(CFLint.java:543)
        at com.cflint.CFLint.processStack(CFLint.java:398)
        at com.cflint.CFLint.process(CFLint.java:341)
        at com.cflint.CFLint.scan(CFLint.java:294)
        at com.cflint.CFLint.scan(CFLint.java:280)
        at com.cflint.CFLint.scan(CFLint.java:280)
        at com.cflint.CFLint.scan(CFLint.java:204)
        at com.cflint.api.CFLintAPI.scan(CFLintAPI.java:66)
        at com.cflint.cli.CFLintCLI.execute(CFLintCLI.java:376)
        at com.cflint.cli.CFLintCLI.main(CFLintCLI.java:343)`

**Comment by ryaneberly** [comment]
Can you provide an example of the code that reproduces the issue?

**Comment by spanteleyko** [comment]
I have an example function:
`<cffunction name="SetFilterStartDate" access="public">
		<cfargument name="StructVar" type="string" required="Yes">
		<cfargument name="start_date" type="string" required="Yes">
		
		<cfscript>
			Evaluate("#arguments.StructVar#").start_date = arguments.start_date;
		</cfscript>
	</cffunction>`
